### ISSUE TITLE
remove text mining content from instructions-template.Rmd?

### ISSUE THREAD

**Issue by jrosen48** [laser-institute/lab-templates#2]
to make this more generic/easily adaptable

https://github.com/laser-institute/templates/blob/main/labs/instructions-template.Rmd

**Comment by sbkellogg** [comment]
go for it. I'll send TM Lab Part 1 to you both today anyways that can be used as an example for filling out each section.

**Comment by sbkellogg** [comment]
Removed text mining examples, generic now
